site_name: champagneSADEZLAN
theme:
  name: mkdocs

plugings:
  - mkdocstring:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true

nav:
  - Home: index.md
  - API:
      - Glass : api/glass.md
      - Radius function: api/radius.md
      - Weather: api/weather.md
      - Expected lambda: api/expected_lambda.md
      - Simulation: api/simulation.md
